python request_new_timesheet_logs.py
python request_new_timesheet.py
python request_new_customfield_items.py
python request_new_geolocs.py
python request_new_customfields.py
python request_new_jobcodes.py
python request_new_employees.py

python upload_employees.py
python upload_jobcodes.py
python upload_customfields.py
python upload_geolocs.py
python upload_customfield_items.py
python upload_timesheet.py
python upload_timesheet_log.py
